import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/Providers";
import Head from "next/head";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BETAFORE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        {/* <Head>
          <link
            href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.css"
            rel="stylesheet"
          />
          <script
            dangerouslySetInnerHTML={{
              __html: `
                if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                  document.documentElement.classList.add('dark');
                  localStorage.setItem('color-theme', 'dark')
                } else {
                  document.documentElement.classList.remove('dark')
                  localStorage.setItem('color-theme', 'light')
                }
              `,
            }}
          />
        </Head> */}
        <Script
          id="m"
          dangerouslySetInnerHTML={{
            __html: `
                if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                  document.documentElement.classList.add('dark');
                  localStorage.setItem('color-theme', 'dark')
                } else {
                  document.documentElement.classList.remove('dark')
                  localStorage.setItem('color-theme', 'light')
                }
              `,
          }}
        />
        <body className={inter.className}>
          {children}
          {/* <script
            src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.js"
            async
          /> */}
        </body>
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.js" />
      </html>
    </Providers>
  );
}
